# Generated by Django 3.1.2 on 2020-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img2txt', '0002_auto_20201007_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img2txt'),
        ),
    ]
